### PR TITLE
Auto-Prefixing and Linting CSS

### LINKED ISSUE #59: Improve Website Code
Per @Inoxia25's comment: Lines 18-26 are repeated many times in this file, maybe the code could be refactored? Should use using comma seperators. 

Also, change AnimationName and .css-selector to something more semantic?

### LINKED ISSUE #73: Asks for GithubToken when `-lighthouse` is called
When I just use the `-lighthouse` command, without using any of the github commands and entering the GithubToken, the bot asks to enter the token. Along with this, the lighthouse feature is not working, as mentioned in issue #69 

image

### PR DESCRIPTION
**Pull request by louisefindlay23**
### Why This PR Adds Value

Allows us to write better CSS in accordance with best practises and adds necessary vendor prefixes to target different browsers

Also fixes #73.

### What This PR Adds

- Adds autoprefixer, postcss-cli and stylelint NPM modules
- Adds .stylelintrc.json file to define Stylelint rules
- Adds a new build command in npm run autoprefixer (but is also included in npm start for simplicity)
- **Note:** Need to run `npm install --dev` and install Stylelint [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=stylelint.vscode-stylelint) or run Stylelint through the CLI - `npx stylelint "**/*.css"`

### Screenshot

N/A - Code Change

### How This PR Could Be Improved

- **Watch Command** - Nodemon could be used to start a live-reload server (means we don't stop and start node server when developing) and postcss-cli could be ran in watch mode to then automatically run autoprefixer when CSS is changed.

### Issue This PR Closes

This closes #59.

### CODE REVIEW

**Review by Inoxia25 — CHANGES_REQUESTED** [review]
@louisefindlay23 good job, but in the `.home.css` file, there seem to be some merge conflicts, and could you add back all the animation styles like the `-moz-animation`, back to the css file? They enable animation across all different browsers( thus moz for firefox)

**Comment by louisefindlay23** [comment]
Sure, will take a look at the merge conflicts.

According to [CanIUse](https://caniuse.com/css-animation), 97.24% of browser versions can use CSS Animation unprefixed and for the remaining 2.73% nearly all work with the -webkit prefix. Only those who haven't updated their web browser since 2012 or use Opera Mini aren't covered See image below.

CanIUse Animation

Happy to add them back in though if you prefer.

**Review by Inoxia25 — CHANGES_REQUESTED** [review]
hey could you maybe change the class name `.css-selector` to the previous class name `background-gradient` or something like that? ? It will make the code more semantic and easier to read :grimacing:

**Review by Inoxia25 — APPROVED** [review]
hey could you maybe change the class name `.css-selector` to the previous class name `background-gradient` or something like that? ? It will make the code more semantic and easier to read :grimacing:

**Pull request merged**
