### PR TITLE
Adds Hot Reloading

### LINKED ISSUE #75: Hot-Reload Node Server
Add a dev or watch NPM command and install `nodemon` to reload the server when code is changed. Then run `postcss-cli` in watch mode to then automatically run `autoprefixer` when CSS is changed.

### PR DESCRIPTION
**Pull request by louisefindlay23**
### Why This PR Adds Value

Adds `nodemon` package so the server is automatically reloaded whenever a change to a `.js` file occurs.

### What This PR Adds

- Adds `nodemon` package to `package.json` as a `devDependency`
-  Adds `nodemonConfig` to `package.json` to set `nodemon` to only watch `.js` files
- Adds a `watch` command as a `npm` script to run `nodemon`
- Alters the `npm start` script to add the `watch` script to `npm start`

### Issue This PR Closes

This closes #75.

### CODE REVIEW

**Review by dtemir — APPROVED** [review]
Looks like something useful :)

**Comment by louisefindlay23** [comment]
> Looks like something useful :)

Thanks for approving. Due to the branch protection, merging requires an approving review. Do you mind if I tag you for further PRs I make?

**Comment by dtemir** [comment]
Of course! Feel free to ping me. Maybe I'll learn a couple of things from you (my JS skills stagnated after we finished this project).

Do you want me to merge PR's though or should I just leave that for you?

**Comment by louisefindlay23** [comment]
Thanks a lot. Feel free to merge.

**Pull request merged**
