### PR TITLE
Database Setup

### LINKED ISSUE #26: Improve Information Storage
Find and implement a better way of storing information for the bot such as GitHub Personal Access Tokens and repo information such as repo names, issue numbers and comment IDs.

**Requirements:**

Must be unique to each user (can't be reused by other users) so not the current `.txt` file solution yet stored for future use so user don't need to provide GitHub Token for each request or discussion and issue number every time.

The data should ideally be persistent but unique to each user, accessible whenever/wherever we need.

**Options:**

- Research if there is some kind of `localStorage` for Discord - @Inoxia25 

- Could do it how we did before just obtaining token from user but then A) it gets reset if we need to restart the bot for any reason (updates etc) and B) we’d need to figure out how to access the token and other info in other command.js files - [`Module.exports` Tutorial](https://www.sitepoint.com/understanding-module-exports-exports-node-js/)

- MongoDB database to store data in a collection with unique username name of Discord User via Discord API?

**Thoughts:**

I think DB may be the way to go since it’s an established solution or we could try and export vars from other .js files but not sure how that would work since we’re not running a function every time to obtain the info.

### PR DESCRIPTION
**Pull request by dtemir**
### Why This PR Adds Value

We need to store GitHub tokens for each user.

### What This PR Adds

- Used CockroachDB Sequelize approach in `github-info.js` to connect to the database and fetch GitHub tokens for users
- Fixed pull conflicts with staging for future merge (please don't delete my stuff from `.gitignore`)

#### Setting up the token
Screenshot from 2021-08-09 20-35-01

#### Getting the token
Screenshot from 2021-08-09 20-35-10

#### No token

Screenshot from 2021-08-09 20-43-10

### How This PR Could Be Improved

- This PR must be improved by setting that token as some sort of a "Global Variable" in `main.js` that we will pass with everything else: ```client.commands.get(command).execute(command, message, args)```
- I need to figure out how to extract the variable from `async/await kind of function` to be able to use it normal and standard way

### Issue This PR Closes

This closes #26

### CODE REVIEW

**Review by louisefindlay23 — CHANGES_REQUESTED** [review]
@dtemir, great work but can you change the PR to merge into staging instead of main so I can approve and merge?

So the fetchGithubToken function works, but we just need to module.exports it?

If so, the code I wrote in github.js might be helpful (for the Code Refactor PR) because I did something similar for obtaining the GitHub token (with the old method).

**Comment by dtemir** [comment]
@louisefindlay23 thanks for pointing out that we need it merged to staging. 

The fetchGitHubToken works, but I can't figure out how to get the value from the asynchronous function to be used in regular functions. Do you mean you obtain github token in `github.js`? I'm just seeing a function that sends a message to the author. Could you send me a link to what part you're talking about?

**Comment by louisefindlay23** [comment]
@dtemir, https://github.com/MLH-Fellowship/gitcord-bot/blob/staging/github.js for module.exports (not async/await so not exactly the same) and https://github.com/MLH-Fellowship/gitcord-bot/blob/staging/commands/github-post-comment.js#L14 but thought it might be helpful?

**Review by louisefindlay23 — APPROVED** [review]
Awesome work, @dtemir. Glad our pair programming sessions helped. Happy to help with `module.exports`.

**Pull request merged**
